package view;

import controler.ClienteDAO;
import controler.FilmeDAO;
import controler.LocacaoDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Filme;
import model.Locacao;

/**
 *
 * @author Quemuel
 */
public class FormVisualizar extends javax.swing.JFrame {
    
    public static List<Cliente> clientes = new ArrayList();
    public static List<Filme> filmes = new ArrayList();
    public static List<Locacao> locacoes = new ArrayList();
    public static int parameter;
    
    /**
     * Creates new form FormVisualizar
     */
    public FormVisualizar(int parameter) {
        this.parameter = parameter;
        initComponents();
        this.setLocationRelativeTo(null);
        preencherTabela(parameter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCadastros = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        lblPesquisar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tblCadastros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblCadastros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCadastrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCadastros);

        txtPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPesquisar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        lblPesquisar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPesquisar.setText("Pesquisar nome");
        lblPesquisar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        preencherTabela(parameter);
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void tblCadastrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCadastrosMouseClicked
        
        int lines = tblCadastros.getSelectedRow();
        
        if(parameter == 0){
            FormCadastrarCliente alterar_cliente = new FormCadastrarCliente(
                tblCadastros.getValueAt(lines,0).toString(),
                tblCadastros.getValueAt(lines,1).toString(),
                tblCadastros.getValueAt(lines,2).toString(),
                tblCadastros.getValueAt(lines,3).toString(),
                tblCadastros.getValueAt(lines,4).toString()
            );
            alterar_cliente.setVisible(true);
            this.dispose();
        }else if(parameter == 1){
            FormCadastrarFilme alterar_filme = new FormCadastrarFilme(
                tblCadastros.getValueAt(lines,0).toString(),
                tblCadastros.getValueAt(lines,1).toString(),
                tblCadastros.getValueAt(lines,2).toString(),
                tblCadastros.getValueAt(lines,3).toString()
            );
            alterar_filme.setVisible(true);
            this.dispose();
        }else if(parameter == 2){
            FormLocacao alterar_locacao = new FormLocacao(
                tblCadastros.getValueAt(lines,0).toString(),
                tblCadastros.getValueAt(lines,1).toString(),
                tblCadastros.getValueAt(lines,2).toString(),
                tblCadastros.getValueAt(lines,3).toString(),
                tblCadastros.getValueAt(lines,4).toString(),
                tblCadastros.getValueAt(lines,5).toString(),
                tblCadastros.getValueAt(lines,6).toString()
            );
            alterar_locacao.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_tblCadastrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVisualizar(parameter).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JTable tblCadastros;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
    
    private void configurarTabelaClientes(){
        
        DefaultTableModel tbclientes = new DefaultTableModel();
        tbclientes.addColumn("id");
        tbclientes.addColumn("nome");
        tbclientes.addColumn("cpf");
        tbclientes.addColumn("email");
        tbclientes.addColumn("telefone");
        
        for(Cliente cli : clientes){
            tbclientes.addRow(new Object[]{cli.getId(),cli.getNome(),cli.getCpf(),cli.getEmail(),cli.getTelefone()});
        }
        tblCadastros.setModel(tbclientes);
    }
    
    private void configurarTabelaFilmes(){
        
        DefaultTableModel tbfilmes = new DefaultTableModel();
        tbfilmes.addColumn("id");
        tbfilmes.addColumn("nome");
        tbfilmes.addColumn("valor");
        tbfilmes.addColumn("classificação");
        
        for(Filme fi : filmes){
            tbfilmes.addRow(new Object[]{fi.getId(),fi.getNome(),fi.getValor(),fi.getClassificacao()});
        }
        tblCadastros.setModel(tbfilmes);
    }
    
    private void configurarTabelaLocacoes(){
        
        DefaultTableModel tblocacoes = new DefaultTableModel();
        tblocacoes.addColumn("id");
        tblocacoes.addColumn("cliente");
        tblocacoes.addColumn("valor");
        tblocacoes.addColumn("data");
        tblocacoes.addColumn("filme1");
        tblocacoes.addColumn("filme2");
        tblocacoes.addColumn("filme3");
        
        for(Locacao loca : locacoes){
            tblocacoes.addRow(new Object[]{loca.getId(),loca.getCliente(),loca.getValor_total(),loca.getData(),loca.getFilme1(),loca.getFilme2(),loca.getFilme3()});
        }
        tblCadastros.setModel(tblocacoes);
    }
    
    private void preencherTabela(int parameter){
        
        if(parameter == 0){
            if(txtPesquisar.getText().isEmpty()){
                clientes = new ClienteDAO().listar();
            }else{
                clientes = new ClienteDAO().buscarNome(txtPesquisar.getText());
            }
            configurarTabelaClientes();
        }else if(parameter == 1){
            if(txtPesquisar.getText().isEmpty()){
                filmes = new FilmeDAO().listar();
            }else{
                filmes = new FilmeDAO().buscarFilme(txtPesquisar.getText());
            }
            configurarTabelaFilmes();
        }else if(parameter == 2){
            if(txtPesquisar.getText().isEmpty()){
                locacoes = new LocacaoDAO().listar();
            }else{
                locacoes = new LocacaoDAO().buscarLocacao(txtPesquisar.getText());
            }
            configurarTabelaLocacoes();
        }
    }
}
